### ISSUE TITLE
Feature request - inputing coordinates of "target" before a trip; have 2 waypoints (home and trip goal)

### ISSUE THREAD

**Issue by marksev1** [samuelmr/pebble-getback#2]
I would like to use your app for example to help me navigate and see how far some mountain or some other hiking target is located.

It would be really nice if there would be an option to switch between "home" and "target" waypoint, so one could see how far one has to either the starting point or the end point.

**Comment by samuelmr** [comment]
Thanks for the request!

Have you noticed that I already have another Pebble app that might do just what you want: https://github.com/samuelmr/pebble-findcache

It allows you to set multiple targets (via phone) and use simple menu to select from them.

**Comment by marksev1** [comment]
Yes, that seems exactly what i was after, thank you, awesome stuff! Hope you'll support it in the future if pebblers decide to change their api and stuff hehe

**Comment by samuelmr** [comment]
Sure I keep watching the changes and future development in the Pebble APIs.

Check out http://getback.pebbletime.io/ and https://github.com/samuelmr/pebble-getbackintime
